packages:
  - "packages/*"
  - "!packages/__backup__"

onlyBuiltDependencies:
  - esbuild

# Resolve internal dependencies to the local package whenever its version satisfies the range.
linkWorkspacePackages: true
