import type { Address, Hex, Quantity, Hash, Index } from '@/types/shared.types.js';
import type { RpcTransaction } from './transaction.js';

// ============================================================================
// Block types
// ============================================================================

export type Withdrawal = {
    /** Address receiving the withdrawn validator funds. */
    address: Address
    /** Amount withdrawn, denominated in Gwei and encoded as a hex quantity. */
    amount: Quantity
    /** Withdrawal index, encoded as a hex quantity. */
    index: Index
    /** Validator index associated with the withdrawal, encoded as a hex quantity. */
    validatorIndex: Index
}

export type RpcBlock<includeTransactions extends boolean = boolean> = {
    /** Base fee per gas for this block, or null for pre-EIP-1559 blocks. */
    baseFeePerGas: Quantity | null
    /** Total blob gas used by all EIP-4844 transactions in this block. */
    blobGasUsed: Quantity
    /** Legacy proof-of-work difficulty for this block. */
    difficulty: Quantity
    /** Excess blob gas after this block, used for EIP-4844 blob fee calculation. */
    excessBlobGas: Quantity
    /** Extra data included by the block producer. */
    extraData: Hex
    /** Maximum gas allowed in this block. */
    gasLimit: Quantity
    /** Total gas used by all transactions in this block. */
    gasUsed: Quantity
    /** Hash of this block. */
    hash: Hash
    /** Bloom filter for the logs generated by this block. */
    logsBloom: Hex
    /** Address of the block beneficiary, also known as the miner or fee recipient. */
    miner: Address
    /** Mix hash value for this block. */
    mixHash: Hash
    /** Proof-of-work nonce for this block. */
    nonce: Hex
    /** Number of this block, encoded as a hex quantity. */
    number: Quantity
    /** Root of the parent beacon chain block, if returned by the node. */
    parentBeaconBlockRoot?: Hex
    /** Hash of the parent block. */
    parentHash: Hash
    /** Root hash of the receipts trie for this block. */
    receiptsRoot: Hex
    /** Additional seal fields for this block, if returned by the node. */
    sealFields: Hex[]
    /** SHA3 hash of the uncle blocks data. */
    sha3Uncles: Hash
    /** Size of this block in bytes, encoded as a hex quantity. */
    size: Quantity
    /** Root hash of the final state trie after this block. */
    stateRoot: Hash
    /** Unix timestamp for when this block was produced, encoded as a hex quantity. */
    timestamp: Quantity
    /** Total difficulty of the chain up to this block, or null on some post-merge networks. */
    totalDifficulty: Quantity | null
    /** Transaction hashes or full transaction objects, depending on the RPC request flag. */
    transactions?: includeTransactions extends true ? RpcTransaction[] : Hash[]
    /** Root hash of the transactions trie for this block. */
    transactionsRoot: Hash
    /** Hashes of uncle blocks included in this block. */
    uncles: Hash[]
    /** Validator withdrawals included in this block, if withdrawals are supported by the chain. */
    withdrawals?: Withdrawal[]
    /** Root hash of the withdrawals trie, if withdrawals are supported by the chain. */
    withdrawalsRoot?: Hex
}